"""Rebuild pneumonia_colab.ipynb.

Notebook structure:
  - Setup (clone, install, Drive mount, dataset)
  - Smoke test
  - Three ablation sweeps (depth; stride/padding/activation; overfitting)
  - 5-fold champion run + medical KPI evaluation
  - Mixup/CutMix/Manifold demo
  - Transfer-learning comparison

Run:
    python _helpers/build_colab_notebook.py
"""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "pneumonia_colab.ipynb"


def md(text: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": text}


def code(text: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": text,
    }


CELLS = [
    md(
        "# Pneumonia detection — CNN design study\n"
        "\n"
        "This notebook walks three ablation sweeps over a custom from-scratch CNN, "
        "then trains and evaluates a 5-fold champion ensemble plus a transfer-learning "
        "comparison baseline.\n"
        "\n"
        "| # | Sweep | Varies |\n"
        "|---|-------|--------|\n"
        "| A1 | Depth | number of conv-pool blocks |\n"
        "| A2 | Stride / padding / activation | architectural micro-choices |\n"
        "| A3 | Regularisation | dropout / BN / L2 / augmentation / combinations |\n"
        "\n"
        "The custom CNN is parametric (`pneumonia_cnn_custom.py`): every architectural choice "
        "is a CLI flag, so each ablation row is one shell invocation. Train/val/test discipline: "
        "test is touched only at the end of each row.\n"
        "\n"
        "## Hardware\n"
        "*Runtime → Change runtime type → H100 GPU* (Pro+ tier or pay-as-you-go compute units).\n"
        "\n"
        "## Time estimate (H100)\n"
        "- Setup + dataset: ~3 min (network-bound, unchanged across GPUs)\n"
        "- Smoke test: ~30 s\n"
        "- A1 depth ablation (4 rows × 20 epochs): ~6 min\n"
        "- A2 stride/padding/activation (6 rows): ~9 min\n"
        "- A3 overfitting (6 rows): ~9 min\n"
        "- Champion 5-fold + KPIs + curves + Grad-CAM: ~10 min\n"
        "- Mixup demo (display): instant\n"
        "- Transfer-learning comparison (ResNet50 @ 288, 5-fold + eval): ~8 min\n"
        "- BiomedCLIP linear probe (PubMed-domain features): ~4 min\n"
        "- RAD-DINO linear probe (chest-X-ray-domain features): ~5 min\n"
        "- **Total: ~55 min on H100**\n"
        "\n"
        "*Reference for context*: same pipeline takes ~3 h on free T4, ~1 h on A100, "
        "~30+ h on AMD Vega 64 + DirectML.\n"
        "\n"
        "All ablation cells are **incrementally resumable** — a row whose "
        "`runs/<name>/summary.json` already exists is skipped (a tiny shell wrapper handles this)."
    ),
    md("## 1. Clone repo + verify GPU"),
    code(
        "!nvidia-smi --query-gpu=name,memory.total --format=csv,noheader\n"
        "%cd /content\n"
        "!git clone https://github.com/Cyberwookie69/Pneumonia-xray-training.git\n"
        "%cd /content/Pneumonia-xray-training"
    ),
    md(
        "## 2. Install dependencies\n"
        "\n"
        "Colab already has PyTorch with CUDA. We add the few extras the project uses."
    ),
    code("!pip install -q timm grad-cam opencv-python-headless kaggle"),
    md(
        "## 3. Mount Drive + load Kaggle credentials (recommended)\n"
        "\n"
        "Mounts Google Drive, copies `kaggle.json` from `My Drive/kaggle.json` to `~/.kaggle/` "
        "(if present), and sets `PNEUMONIA_RUNS` to a Drive folder so checkpoints survive "
        "session timeouts. If you haven't placed `kaggle.json` on Drive yet, this cell still "
        "works (sets up persistence) and you fall through to section 4 to upload it manually."
    ),
    code(
        "from google.colab import drive\n"
        "import os, shutil\n"
        "\n"
        "drive.mount('/content/drive')\n"
        "\n"
        "src = '/content/drive/MyDrive/kaggle.json'\n"
        "kaggle_dir = os.path.expanduser('~/.kaggle')\n"
        "if os.path.exists(src):\n"
        "    os.makedirs(kaggle_dir, exist_ok=True)\n"
        "    shutil.copy(src, os.path.join(kaggle_dir, 'kaggle.json'))\n"
        "    os.chmod(os.path.join(kaggle_dir, 'kaggle.json'), 0o600)\n"
        "    print('✓ kaggle.json copied from Drive — section 4 can be skipped')\n"
        "else:\n"
        "    print(f'⚠ {src} not found — run section 4 to upload it manually.')\n"
        "\n"
        "os.makedirs('/content/drive/MyDrive/pneumonia_runs', exist_ok=True)\n"
        "os.environ['PNEUMONIA_RUNS'] = '/content/drive/MyDrive/pneumonia_runs'\n"
        "print(f\"Runs will be saved to: {os.environ['PNEUMONIA_RUNS']}\")\n"
        "\n"
        "# HuggingFace token — read from Colab Secrets (recommended) or env var.\n"
        "# Required for gated models like RAD-DINO; harmless if absent (used as a\n"
        "# rate-limit booster for BiomedCLIP too).\n"
        "try:\n"
        "    from google.colab import userdata\n"
        "    hf_token = userdata.get('HF_TOKEN')\n"
        "except Exception:\n"
        "    hf_token = os.environ.get('HF_TOKEN')\n"
        "if hf_token:\n"
        "    os.environ['HF_TOKEN'] = hf_token\n"
        "    os.environ['HUGGING_FACE_HUB_TOKEN'] = hf_token  # transformers/open_clip fallback\n"
        "    print('✓ HF_TOKEN loaded — gated models (RAD-DINO) accessible')\n"
        "else:\n"
        "    print('⚠ No HF_TOKEN in Colab Secrets — section 17 (RAD-DINO) will fall '\n"
        "          'back to interactive login. Add HF_TOKEN to the 🔑 Secrets panel '\n"
        "          'to skip the prompt every session.')"
    ),
    md(
        "## 4. Kaggle authentication via upload widget (fallback)\n"
        "\n"
        "Skip this cell if section 3 already loaded `kaggle.json`."
    ),
    code(
        "import os\n"
        "if os.path.exists(os.path.expanduser('~/.kaggle/kaggle.json')):\n"
        "    print('✓ kaggle.json already in place — no need to upload')\n"
        "else:\n"
        "    from google.colab import files\n"
        "    uploaded = files.upload()\n"
        "    !mkdir -p ~/.kaggle && cp kaggle.json ~/.kaggle/ && chmod 600 ~/.kaggle/kaggle.json"
    ),
    md("## 5. Download dataset (~2.3 GB, ~1 min)"),
    code("!python pneumonia.py"),
    md(
        "## 6. Smoke test — one fast custom-CNN run\n"
        "\n"
        "Verifies that data loading + model + training loop works end-to-end before "
        "we burn time on the ablations. 5 epochs only, default 4-block ReLU CNN."
    ),
    code(
        "!python pneumonia_cnn_custom.py --run_name smoke_test --epochs 5 --num_workers 6"
    ),
    md(
        "---\n"
        "## 7. Ablation A1 — Number of conv-pool building blocks\n"
        "\n"
        "Holds activation=ReLU, padding=same, stride_mode=pool, no regularisation. "
        "Varies only `n_blocks ∈ {2, 3, 4, 5}`. Each row is a single 88/12 train/val "
        "split (fast, fine for hyperparameter selection); the champion will be 5-fold."
    ),
    code(
        "import os, subprocess, json\n"
        "\n"
        "RUNS_ROOT = os.environ.get('PNEUMONIA_RUNS', 'runs')\n"
        "\n"
        "def run_if_missing(run_name, args):\n"
        "    summary = f'{RUNS_ROOT}/{run_name}/summary.json'\n"
        "    if os.path.exists(summary):\n"
        "        print(f'✓ {run_name} already done — skipping')\n"
        "        return\n"
        "    cmd = ['python', 'pneumonia_cnn_custom.py', '--run_name', run_name] + args\n"
        "    print('>>>', ' '.join(cmd))\n"
        "    subprocess.run(cmd, check=True)\n"
        "\n"
        "for n in [2, 3, 4, 5]:\n"
        "    run_if_missing(f'a1_d{n}', ['--n_blocks', str(n), '--epochs', '20', '--num_workers', '6'])"
    ),
    code(
        "# Collect A1 results + add a Glorot-init control on the winning depth\n"
        "# (He et al. 2015 argue Glorot fails with stacked ReLUs at depth ≥ 4 —\n"
        "#  this is the controlled comparison that makes the depth ablation a\n"
        "#  *finding*, not just a tuning sweep).\n"
        "import json, os, math\n"
        "from pathlib import Path\n"
        "\n"
        "RUNS_ROOT = os.environ.get('PNEUMONIA_RUNS', 'runs')\n"
        "\n"
        "best_n, best_va = 4, 0.0\n"
        "for n in [2, 3, 4, 5]:\n"
        "    s = json.load(open(f'{RUNS_ROOT}/a1_d{n}/summary.json'))\n"
        "    if s['best_val_acc'] > best_va:\n"
        "        best_va, best_n = s['best_val_acc'], n\n"
        "\n"
        "# Glorot control on the winning depth\n"
        "run_if_missing(f'a1_d{best_n}_glorot',\n"
        "               ['--n_blocks', str(best_n), '--init', 'glorot',\n"
        "                '--epochs', '20', '--num_workers', '6'])\n"
        "\n"
        "# === A1 results table with binomial noise-floor annotation ===\n"
        "rows = []\n"
        "for label, run in [(f'{n}', f'a1_d{n}') for n in [2, 3, 4, 5]] + \\\n"
        "                  [(f'{best_n} (Glorot)', f'a1_d{best_n}_glorot')]:\n"
        "    s = json.load(open(f'{RUNS_ROOT}/{run}/summary.json'))\n"
        "    rows.append((label, s['architecture']['n_params'], s['best_val_acc'],\n"
        "                 s['test_acc'], s['training']['elapsed_min']))\n"
        "\n"
        "# Binomial noise floor on test accuracy: sigma = sqrt(p*(1-p)/n)\n"
        "p = max(r[3] for r in rows); n_test = 624\n"
        "sigma_test = math.sqrt(p * (1 - p) / n_test)\n"
        "print(f'{\"n_blocks\":>14}{\"params\":>12}{\"val_acc\":>10}{\"test_acc\":>10}{\"min\":>8}')\n"
        "for lbl, params, va, ta, mn in rows:\n"
        "    print(f'{lbl:>14}{params:>12,}{va:>10.4f}{ta:>10.4f}{mn:>8.1f}')\n"
        "print()\n"
        "print(f'Binomial noise floor on test acc (n={n_test}): '\n"
        "      f'sigma ~= {sigma_test:.4f} ({sigma_test*100:.2f} pp)')\n"
        "print(f'-> any pairwise delta below ~{2*sigma_test*100:.2f} pp '\n"
        "      f'is statistically indistinguishable.')"
    ),
    md(
        "---\n"
        "## 8. Ablation A2 — Stride / padding / activation\n"
        "\n"
        "Holds depth at the A1 winner (default n_blocks=4 — adjust below if A1 picked otherwise). "
        "Varies activation, padding, and stride_mode. Six representative cells; full Cartesian "
        "(3×2×2 = 12) would add little additional information."
    ),
    code(
        "# Pick the A1 winner (largest test_acc among 2..5 blocks). Default to 4 if tie.\n"
        "import json, os\n"
        "RUNS_ROOT = os.environ.get('PNEUMONIA_RUNS', 'runs')\n"
        "best_n, best_acc = 4, 0.0\n"
        "for n in [2, 3, 4, 5]:\n"
        "    s = json.load(open(f'{RUNS_ROOT}/a1_d{n}/summary.json'))\n"
        "    if s['test_acc'] > best_acc:\n"
        "        best_acc, best_n = s['test_acc'], n\n"
        "print(f'A1 winner: n_blocks={best_n} (test_acc={best_acc:.4f})')\n"
        "\n"
        "A2_RUNS = [\n"
        "    # name              activation padding  stride_mode\n"
        "    ('a2_relu_same_pool',     'relu',  'same',  'pool'),\n"
        "    ('a2_leaky_same_pool',    'leaky', 'same',  'pool'),\n"
        "    ('a2_gelu_same_pool',     'gelu',  'same',  'pool'),\n"
        "    ('a2_relu_valid_pool',    'relu',  'valid', 'pool'),\n"
        "    ('a2_relu_same_strided',  'relu',  'same',  'strided'),\n"
        "    ('a2_gelu_same_strided',  'gelu',  'same',  'strided'),\n"
        "]\n"
        "for name, act, pad, sm in A2_RUNS:\n"
        "    run_if_missing(name, ['--n_blocks', str(best_n),\n"
        "                          '--activation', act, '--padding', pad,\n"
        "                          '--stride_mode', sm,\n"
        "                          '--epochs', '20', '--num_workers', '6'])"
    ),
    code(
        "# A2 results table\n"
        "rows = []\n"
        "for name, act, pad, sm in A2_RUNS:\n"
        "    s = json.load(open(f'{RUNS_ROOT}/{name}/summary.json'))\n"
        "    rows.append((act, pad, sm, s['best_val_acc'], s['test_acc']))\n"
        "print(f'{\"activation\":>11}{\"padding\":>9}{\"stride\":>10}{\"val_acc\":>10}{\"test_acc\":>10}')\n"
        "for r in rows:\n"
        "    print(f'{r[0]:>11}{r[1]:>9}{r[2]:>10}{r[3]:>10.4f}{r[4]:>10.4f}')"
    ),
    md(
        "---\n"
        "## 9. Ablation A3 — Regularisation / overfitting controls\n"
        "\n"
        "Holds the A1+A2 winner architecture. Varies regularisation: none / BN / dropout / L2 / "
        "augmentation / combined. The 'none' row is the same architecture without any "
        "anti-overfit mechanism — expect the largest train-vs-val gap there."
    ),
    code(
        "# Pick the A2 winner from the table above. We assume the highest-test row.\n"
        "best_a2 = None; best_acc = 0.0\n"
        "for name, act, pad, sm in A2_RUNS:\n"
        "    s = json.load(open(f'{RUNS_ROOT}/{name}/summary.json'))\n"
        "    if s['test_acc'] > best_acc:\n"
        "        best_acc = s['test_acc']\n"
        "        best_a2 = (act, pad, sm)\n"
        "act, pad, sm = best_a2\n"
        "print(f'A2 winner: act={act}, pad={pad}, stride_mode={sm} (test_acc={best_acc:.4f})')\n"
        "\n"
        "BASE = ['--n_blocks', str(best_n), '--activation', act, '--padding', pad,\n"
        "        '--stride_mode', sm, '--epochs', '20', '--num_workers', '6']\n"
        "\n"
        "A3_RUNS = [\n"
        "    ('a3_none',    BASE),\n"
        "    ('a3_bn',      BASE + ['--use_bn']),\n"
        "    ('a3_dropout', BASE + ['--use_dropout', '0.3']),\n"
        "    ('a3_l2',      BASE + ['--weight_decay', '1e-4']),\n"
        "    ('a3_aug',     BASE + ['--augment']),\n"
        "    ('a3_combo',   BASE + ['--use_bn', '--use_dropout', '0.3', '--augment',\n"
        "                           '--weight_decay', '1e-4',\n"
        "                           '--early_stop_patience', '5']),\n"
        "]\n"
        "for name, args in A3_RUNS:\n"
        "    run_if_missing(name, args)"
    ),
    code(
        "# A3 results table — focus on the train-vs-val gap as a regularisation indicator\n"
        "rows = []\n"
        "for name, _ in A3_RUNS:\n"
        "    s = json.load(open(f'{RUNS_ROOT}/{name}/summary.json'))\n"
        "    h = json.load(open(f'{RUNS_ROOT}/{name}/history.json'))\n"
        "    final_train = h['train_acc'][-1] if h['train_acc'] else 0.0\n"
        "    gap = final_train - s['best_val_acc']\n"
        "    rows.append((name.replace('a3_', ''), final_train, s['best_val_acc'],\n"
        "                 gap, s['test_acc']))\n"
        "print(f'{\"reg\":>10}{\"train_acc\":>11}{\"val_acc\":>10}{\"gap\":>8}{\"test_acc\":>10}')\n"
        "for r in rows:\n"
        "    print(f'{r[0]:>10}{r[1]:>11.4f}{r[2]:>10.4f}{r[3]:>8.4f}{r[4]:>10.4f}')"
    ),
    md(
        "---\n"
        "## 10. Champion — train winning configuration with 5-fold CV\n"
        "\n"
        "Combines the A1, A2, and A3 winners. Trains 5 folds for a robust ensemble result on "
        "the official Kaggle test set."
    ),
    code(
        "# Pick A3 winner (highest test_acc — but feel free to override based on the table)\n"
        "best_a3, best_acc = None, 0.0\n"
        "for name, args in A3_RUNS:\n"
        "    s = json.load(open(f'{RUNS_ROOT}/{name}/summary.json'))\n"
        "    if s['test_acc'] > best_acc:\n"
        "        best_acc = s['test_acc']; best_a3 = (name, args)\n"
        "print(f'A3 winner: {best_a3[0]} (test_acc={best_acc:.4f})')\n"
        "champion_extra = best_a3[1]\n"
        "\n"
        "# Train 5 folds; each saves test_probs.npy that we ensemble below.\n"
        "for fold in range(5):\n"
        "    args = champion_extra + ['--n_folds', '5', '--fold', str(fold)]\n"
        "    run_if_missing(f'champion_f{fold}', args)"
    ),
    md(
        "## 11. Champion — medical KPI evaluation (Sens / Spec / AUROC / ECE)\n"
        "\n"
        "Ensembles the 5 fold probability predictions and prints the four medical KPIs at "
        "three operating points: default τ=0.5, val-tuned best-accuracy τ, and "
        "sensitivity-targeted τ ≥ 0.97."
    ),
    code(
        "import numpy as np, json, os\n"
        "RUNS_ROOT = os.environ.get('PNEUMONIA_RUNS', 'runs')\n"
        "\n"
        "probs = [np.load(f'{RUNS_ROOT}/champion_f{i}/test_probs.npy') for i in range(5)]\n"
        "labels = np.load(f'{RUNS_ROOT}/champion_f0/test_labels.npy').astype(int)\n"
        "ensemble_probs = np.mean(np.stack(probs, axis=0), axis=0)\n"
        "\n"
        "# Save ensemble probs+labels so _helpers/medical_kpis.py can read them\n"
        "ens_dir = f'{RUNS_ROOT}/champion_ensemble'\n"
        "os.makedirs(ens_dir, exist_ok=True)\n"
        "np.save(f'{ens_dir}/test_probs.npy', ensemble_probs)\n"
        "np.save(f'{ens_dir}/test_labels.npy', labels)\n"
        "\n"
        "!python _helpers/medical_kpis.py --run {ens_dir}"
    ),
    md(
        "## 12. Champion — learning curves\n"
        "\n"
        "One curve per fold, plus the per-fold final test accuracy."
    ),
    code(
        "import json, matplotlib.pyplot as plt\n"
        "from matplotlib.ticker import MaxNLocator\n"
        "\n"
        "fig, axes = plt.subplots(1, 2, figsize=(13, 5))\n"
        "for fold in range(5):\n"
        "    h = json.load(open(f'{RUNS_ROOT}/champion_f{fold}/history.json'))\n"
        "    epochs = list(range(1, len(h['train_loss']) + 1))\n"
        "    axes[0].plot(epochs, h['train_loss'], alpha=0.6, label=f'fold{fold} train')\n"
        "    axes[0].plot(epochs, h['val_loss'], alpha=0.6, linestyle='--', label=f'fold{fold} val')\n"
        "    axes[1].plot(epochs, h['train_acc'], alpha=0.6, label=f'fold{fold} train')\n"
        "    axes[1].plot(epochs, h['val_acc'], alpha=0.6, linestyle='--', label=f'fold{fold} val')\n"
        "for ax in axes:\n"
        "    ax.set_xlabel('epoch')\n"
        "    ax.xaxis.set_major_locator(MaxNLocator(integer=True))\n"
        "    ax.legend(fontsize=7)\n"
        "axes[0].set_title('Loss'); axes[1].set_title('Accuracy')\n"
        "plt.tight_layout(); plt.savefig(f'{RUNS_ROOT}/champion_ensemble/learning_curves.png', dpi=110)\n"
        "plt.show()"
    ),
    md(
        "## 13. Champion — Grad-CAM\n"
        "\n"
        "Where does the champion model look when it predicts pneumonia? Useful for clinician "
        "trust and for catching reliance on dataset artefacts (text annotations, machine IDs).\n"
        "\n"
        "*Reading the figure*: the number under each heatmap is **P(Pneumonia)** — the model's "
        "predicted **certainty** that the scan shows pneumonia, on a 0–1 scale (0.95 = 95 % "
        "certain pneumonia; 0.10 = 90 % certain normal). This is a per-image quantity and is "
        "**not** the same as sensitivity, which is a dataset-level metric reported in §11."
    ),
    code(
        "# Grad-CAM only works with the existing pneumonia_gradcam.py for timm models.\n"
        "# For our custom CNN we draw heatmaps directly via the last conv block's gradients.\n"
        "import torch, json\n"
        "import numpy as np\n"
        "import matplotlib.pyplot as plt\n"
        "from PIL import Image\n"
        "from pneumonia_cnn_custom import CustomCNN, build_transforms\n"
        "from pneumonia_train import DATA_ROOT, list_images\n"
        "\n"
        "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n"
        "\n"
        "summ = json.load(open(f'{RUNS_ROOT}/champion_f0/summary.json'))\n"
        "arch = summ['architecture']\n"
        "model = CustomCNN(n_blocks=arch['n_blocks'], base_channels=arch['base_channels'],\n"
        "                  activation=arch['activation'], padding=arch['padding'],\n"
        "                  stride_mode=arch['stride_mode'], use_bn=arch['use_bn'],\n"
        "                  use_dropout=arch['use_dropout']).to(device)\n"
        "model.load_state_dict(torch.load(f'{RUNS_ROOT}/champion_f0/best_state.pt',\n"
        "                                  map_location=device))\n"
        "model.eval()\n"
        "\n"
        "# Pick 4 test images: 2 NORMAL, 2 PNEUMONIA\n"
        "items = list_images(DATA_ROOT)\n"
        "test_n = [(p, l) for p, l, s in items if s == 'test' and l == 0][:2]\n"
        "test_p = [(p, l) for p, l, s in items if s == 'test' and l == 1][:2]\n"
        "samples = test_n + test_p\n"
        "\n"
        "tf = build_transforms(summ['training']['img_size'], train=False, augment=False)\n"
        "\n"
        "# Hook the last conv block's output and gradient\n"
        "feat_buf, grad_buf = [], []\n"
        "h1 = model.features[-1].conv.register_forward_hook(\n"
        "    lambda m, i, o: feat_buf.append(o.detach()))\n"
        "h2 = model.features[-1].conv.register_full_backward_hook(\n"
        "    lambda m, gi, go: grad_buf.append(go[0].detach()))\n"
        "\n"
        "fig, axes = plt.subplots(2, 4, figsize=(15, 7))\n"
        "for col, (path, label) in enumerate(samples):\n"
        "    img = Image.open(path).convert('L')\n"
        "    img_show = np.array(img.resize((summ['training']['img_size'],) * 2))\n"
        "    x = tf(img).unsqueeze(0).to(device); x.requires_grad_(True)\n"
        "    feat_buf.clear(); grad_buf.clear()\n"
        "    logit = model(x)\n"
        "    model.zero_grad(); logit.sum().backward()\n"
        "    feat = feat_buf[0][0]; grad = grad_buf[0][0]\n"
        "    weights = grad.mean(dim=(1, 2))\n"
        "    cam = torch.relu((weights[:, None, None] * feat).sum(0))\n"
        "    cam = (cam / (cam.max() + 1e-8)).cpu().numpy()\n"
        "    cam_up = np.array(Image.fromarray(cam).resize(img_show.shape[::-1]))\n"
        "    prob_pne = torch.sigmoid(logit).item()\n"
        "    pred = 'Pneumonia' if prob_pne > 0.5 else 'Normal'\n"
        "    truth = 'Pneumonia' if label == 1 else 'Normal'\n"
        "    correct = '✓' if pred == truth else '✗'\n"
        "    axes[0, col].imshow(img_show, cmap='gray')\n"
        "    axes[0, col].set_title(f'true: {truth}'); axes[0, col].axis('off')\n"
        "    axes[1, col].imshow(img_show, cmap='gray')\n"
        "    axes[1, col].imshow(cam_up, cmap='jet', alpha=0.5)\n"
        "    axes[1, col].set_title(f'pred: {pred} {correct}\\n'\n"
        "                           f'P(Pneumonia) = {prob_pne:.2f}',\n"
        "                           fontsize=10)\n"
        "    axes[1, col].axis('off')\n"
        "h1.remove(); h2.remove()\n"
        "plt.tight_layout(); plt.savefig(f'{RUNS_ROOT}/champion_ensemble/gradcam.png', dpi=110)\n"
        "plt.show()"
    ),
    md(
        "---\n"
        "## 14. Other things we tried — Mixup / CutMix / Manifold Mixup demo\n"
        "\n"
        "Generated by `_helpers/_mixup_cutmix_demo.py`. Mixup α=0.2 on the pretrained "
        "track lost 0.64 pp test accuracy — pretrained class boundaries are already "
        "calibrated, so blending samples adds noise rather than regularisation."
    ),
    code(
        "from IPython.display import Image as IPImage, display\n"
        "import os\n"
        "\n"
        "demo_path = '_helpers/mixup_cutmix_demo.png'\n"
        "if not os.path.exists(demo_path):\n"
        "    !python _helpers/_mixup_cutmix_demo.py\n"
        "if os.path.exists(demo_path):\n"
        "    display(IPImage(demo_path))\n"
        "else:\n"
        "    print('Demo image not found. Re-run after dataset has been downloaded.')"
    ),
    md(
        "---\n"
        "## 15. Transfer-learning comparison (ResNet50 + ImageNet)\n"
        "\n"
        "5-fold ResNet50 fine-tuned from ImageNet weights at image size 288. Quantifies "
        "how much pretrained features add on top of our from-scratch design choices. "
        "Comparison baseline against the from-scratch champion above.\n"
        "\n"
        "**Why it stays on the standard pipeline**: the ~8 min cost on H100 is small compared "
        "to the strength of the resulting comparison ('our 4-block CNN reaches X% from scratch; "
        "with ImageNet pretraining the same project reaches Y%')."
    ),
    code(
        "# 5-fold ResNet50 + ImageNet pretrained, ~7 min on H100.\n"
        "# pneumonia_run_folds.py auto-skips folds with an existing summary.json,\n"
        "# so re-running is free if Drive already holds prior results.\n"
        "!python pneumonia_run_folds.py --pretrained --extra='--img_size 288 --num_workers 6'"
    ),
    code(
        "# Eval the transfer-learning ensemble + medical KPIs\n"
        "!python pneumonia_eval.py --ensemble ens_f0,ens_f1,ens_f2,ens_f3,ens_f4 \\\n"
        "    --use_best --num_workers 0 --img_size 288\n"
        "!python _helpers/medical_kpis.py --run $PNEUMONIA_RUNS/ensemble"
    ),

    md(
        "---\n"
        "## 16. Transfer learning — BiomedCLIP (vision-language, biomedical literature pretrained)\n"
        "\n"
        "Linear-probe baseline using **BiomedCLIP** (Microsoft, 2023), a CLIP-style "
        "vision-language model pretrained on ~15M biomedical image-text pairs from "
        "PubMed Open Access. We use only the image encoder, frozen, plus a 5-fold "
        "logistic regression head — the standard linear-probe protocol.\n"
        "\n"
        "**No architecture ablation here**: BiomedCLIP is a fixed pretrained black-box. "
        "Our only tuning surface is the classifier head's regularisation (`C` parameter) "
        "and feature preprocessing.\n"
        "\n"
        "**Leakage caveat**: BiomedCLIP was pretrained on biomedical literature images "
        "from PubMed — illustrations, microscopy, charts, occasional X-rays. Direct "
        "image overlap with the Kermany dataset is unlikely but distribution-level "
        "exposure to chest X-ray statistics is plausible. Less acute than RAD-DINO's "
        "leakage risk (see §17), but worth noting."
    ),
    code(
        "# Install open_clip_torch — BiomedCLIP uses the open_clip API\n"
        "!pip install -q open_clip_torch"
    ),
    code(
        "# Linear-probe BiomedCLIP — features cached on Drive after first run.\n"
        "!python pneumonia_biomedclip.py --run_name biomedclip_ensemble"
    ),
    code(
        "# Medical KPIs on the BiomedCLIP ensemble\n"
        "!python _helpers/medical_kpis.py --run $PNEUMONIA_RUNS/biomedclip_ensemble"
    ),

    md(
        "---\n"
        "## 17. Transfer learning — RAD-DINO (medical-domain pretrained)\n"
        "\n"
        "Linear-probe baseline using **RAD-DINO** (Microsoft, 2024), a Vision Transformer "
        "pretrained on ~877K chest X-rays from MIMIC-CXR, CheXpert, PadChest, NIH ChestX-ray14, "
        "BRAX, and VinDr-CXR. Frozen features + 5-fold logistic regression on top — the standard "
        "evaluation protocol for self-supervised representations.\n"
        "\n"
        "**⚠️ Caveat — possible distribution-level overlap.** The Kermany 2018 dataset "
        "(Guangzhou Women & Children's Medical Center) is *not* in RAD-DINO's published "
        "pretraining list, so direct image overlap is unlikely. However, chest X-ray "
        "datasets share statistical properties (acquisition protocols, equipment, anatomy "
        "distributions). Results from medical-domain pretrained models should therefore be "
        "interpreted with this caveat — the test KPIs are not as cleanly held-out as for the "
        "from-scratch champion or the ResNet50 + ImageNet baseline.\n"
        "\n"
        "**One-time setup**: visit https://huggingface.co/microsoft/rad-dino, accept the "
        "model terms, then either run `huggingface-cli login` once or set the `HF_TOKEN` env "
        "var with a token from https://huggingface.co/settings/tokens."
    ),
    code(
        "# Install transformers if not yet present. HF auth was set up in §3.\n"
        "!pip install -q transformers accelerate\n"
        "\n"
        "import os\n"
        "if not os.environ.get('HF_TOKEN') and not os.environ.get('HUGGING_FACE_HUB_TOKEN'):\n"
        "    # §3 didn't load a token — fall back to interactive login (one prompt).\n"
        "    from huggingface_hub import login\n"
        "    print('No HF_TOKEN set — interactive login (will prompt for a token).')\n"
        "    login()\n"
        "else:\n"
        "    print('✓ HF_TOKEN already loaded (from §3)')"
    ),
    code(
        "# Linear-probe RAD-DINO — features cached on Drive after first run.\n"
        "!python pneumonia_rad_dino.py --run_name rad_dino_ensemble"
    ),
    code(
        "# Medical KPIs on the RAD-DINO ensemble\n"
        "!python _helpers/medical_kpis.py --run $PNEUMONIA_RUNS/rad_dino_ensemble"
    ),

    # ===================================================================
    # Mini-report synthesis
    # ===================================================================

    md(
        "---\n"
        "# Mini-report — synthesis\n"
        "\n"
        "Self-contained walkthrough of the full study, generated from the JSON "
        "artefacts that the cells above wrote to Drive. Cells are robust to missing "
        "data: an ablation row that hasn't been trained yet shows as a dash."
    ),
    md(
        "## 18. Methodology overview\n"
        "\n"
        "A five-stage pipeline. The test set is held out from every tuning decision "
        "until the final eval; ablations only apply to tracks where we have control "
        "over the architecture."
    ),
    md(
        "### Optional — render the diagram via Gemini's Nano Banana (gemini-2.5-flash-image)\n"
        "\n"
        "If you have a Gemini API key in Colab Secrets as `GEMINI_API_KEY`, the cell "
        "below regenerates the diagram via the Nano Banana image-generation API. "
        "If the secret is absent, it skips and the next cell falls back to the static "
        "matplotlib version that ships with the repo.\n"
        "\n"
        "*Get a free key at https://aistudio.google.com/app/apikey → add via the 🔑 "
        "Secrets panel in Colab → toggle 'Notebook access' on.*"
    ),
    code(
        "import os\n"
        "from IPython.display import Image as IPImage, display\n"
        "\n"
        "# Resolve key from Colab Secrets if available\n"
        "try:\n"
        "    from google.colab import userdata\n"
        "    api_key = userdata.get('GEMINI_API_KEY')\n"
        "except Exception:\n"
        "    api_key = os.environ.get('GEMINI_API_KEY')\n"
        "\n"
        "if not api_key:\n"
        "    print('No GEMINI_API_KEY found — skipping Nano Banana, will use static fallback.')\n"
        "else:\n"
        "    !pip install -q google-genai\n"
        "    from google import genai\n"
        "    import base64, mimetypes\n"
        "    from io import BytesIO\n"
        "    from PIL import Image as PILImage\n"
        "\n"
        "    PROMPT = '''A clean, professional infographic for an academic medical-AI report.\n"
        "The diagram shows a 5-stage methodology pipeline, arranged top-to-bottom on a white background.\n"
        "Modern sans-serif typography, thin coloured borders per stage, downward arrows between stages,\n"
        "no shadows, no decorative elements, landscape 16:10 aspect ratio.\n"
        "\n"
        "STAGE 1 (orange / amber): \"Source data — Kaggle Chest X-Ray Pneumonia (Kermany 2018)\".\n"
        "Three labeled sub-boxes side by side:\n"
        "  • Train: 5,216 images\n"
        "  • Val: 16 images (too small for tuning)\n"
        "  • Test: 624 images (held out)\n"
        "\n"
        "STAGE 2 (green): \"Data preparation\". Two horizontally-arranged sub-boxes:\n"
        "  • Patient-isolation verification (filename namespace check)\n"
        "  • Val redistribution: merge train+val into 5,232 pool → 5-fold StratifiedKFold\n"
        "\n"
        "STAGE 3 (blue): \"Methodology comparison on this dataset\". FOUR parallel approach boxes,\n"
        "each annotated with its ablation depth:\n"
        "  • Custom CNN from scratch — DEEP ablation (A1 depth + A2 stride/padding/activation + A3 regularisation)\n"
        "  • ResNet50 + ImageNet — shallow tuning (LR + batch only)\n"
        "  • BiomedCLIP + linear probe — frozen vision-language features, no architecture ablation\n"
        "  • RAD-DINO + linear probe — frozen medical-pretrained features, no architecture ablation\n"
        "\n"
        "STAGE 4 (purple, DASHED border to indicate future work): \"Generalization to external datasets\".\n"
        "The same four approaches applied to three new datasets:\n"
        "  • NIH ChestX-ray14\n"
        "  • RSNA Pneumonia Detection\n"
        "  • CheXpert\n"
        "Caveat label: \"BiomedCLIP and RAD-DINO carry leakage risk on these datasets — they were\n"
        "  pretrained on (subsets of) the same data. Clean generalization tests use only the\n"
        "  Custom CNN and ResNet50+ImageNet tracks.\"\n"
        "\n"
        "STAGE 5 (red / coral): \"Synthesis\". Three sub-blocks:\n"
        "  • Headline KPI table (Sensitivity, Specificity, AUROC, ECE per approach × dataset)\n"
        "  • Conclusion (which methodology generalizes best, with caveats)\n"
        "  • Future work\n"
        "\n"
        "Render at high resolution suitable for a printed academic report figure.\n"
        "Self-explanatory without caption.\n"
        "'''\n"
        "\n"
        "    client = genai.Client(api_key=api_key)\n"
        "    response = client.models.generate_content(\n"
        "        model='gemini-2.5-flash-image',\n"
        "        contents=PROMPT,\n"
        "    )\n"
        "\n"
        "    saved = False\n"
        "    for part in response.candidates[0].content.parts:\n"
        "        if getattr(part, 'inline_data', None) and part.inline_data.data:\n"
        "            data = part.inline_data.data\n"
        "            if isinstance(data, str):\n"
        "                data = base64.b64decode(data)\n"
        "            img = PILImage.open(BytesIO(data))\n"
        "            out_path = '_helpers/methodology_flow_nano.png'\n"
        "            img.save(out_path)\n"
        "            print(f'Saved Nano Banana render: {out_path} ({img.size[0]}×{img.size[1]})')\n"
        "            display(img)\n"
        "            saved = True\n"
        "            break\n"
        "    if not saved:\n"
        "        print('Nano Banana returned no image — falling back to static version.')\n"
        "        print('Response text:', getattr(response, 'text', '(none)'))"
    ),
    md("### Static fallback (matplotlib version, ships with the repo)"),
    code(
        "from IPython.display import Image as IPImage, display\n"
        "import os\n"
        "\n"
        "fig_path = '_helpers/methodology_flow.png'\n"
        "if not os.path.exists(fig_path):\n"
        "    !python _helpers/_methodology_flow.py\n"
        "display(IPImage(fig_path))"
    ),
    md(
        "### Optional — let Gemini text model draft matplotlib code from JSON data\n"
        "\n"
        "For exploring new chart ideas during the writing phase. Sends a JSON blob "
        "and a chart specification to **gemini-2.5-flash** (text model, not Nano "
        "Banana), gets matplotlib code back, **shows the code for review**, and only "
        "executes it if you flip `RUN_CODE = True` below. Unlike Nano Banana, the "
        "resulting chart is exact — matplotlib runs on the real numbers from the JSON.\n"
        "\n"
        "Edit the `spec` string to ask for whatever chart you want. Re-run; review "
        "the printed code; flip the flag if it looks reasonable; re-run."
    ),
    code(
        "import os, json\n"
        "try:\n"
        "    from google.colab import userdata\n"
        "    api_key = userdata.get('GEMINI_API_KEY')\n"
        "except Exception:\n"
        "    api_key = os.environ.get('GEMINI_API_KEY')\n"
        "\n"
        "if not api_key:\n"
        "    print('No GEMINI_API_KEY — set it in Colab Secrets to enable.')\n"
        "else:\n"
        "    !pip install -q google-genai\n"
        "    from google import genai\n"
        "\n"
        "    # ── Pick the data and the chart spec ─────────────────────────────\n"
        "    kpi_path = f'{RUNS_ROOT}/champion_ensemble/medical_kpis.json'\n"
        "    if not os.path.exists(kpi_path):\n"
        "        print(f'No data at {kpi_path} — train the champion first.')\n"
        "    else:\n"
        "        data = json.load(open(kpi_path))\n"
        "        spec = f'''Render a single matplotlib figure showing the four medical\n"
        "KPIs (sensitivity, specificity, AUROC, 1-ECE) at the best-accuracy operating\n"
        "point. Use a horizontal bar chart, annotate each bar with its value (3\n"
        "decimals), add a dashed vertical line at 0.95 labelled 'clinical screening\n"
        "target'. Title: 'Champion ensemble — medical KPIs at best-accuracy threshold'.\n"
        "Save to {RUNS_ROOT}/champion_ensemble/champion_kpis.png at dpi=120 and call plt.show().\n"
        "Output ONLY a single Python code block, no commentary, no markdown.'''\n"
        "\n"
        "        client = genai.Client(api_key=api_key)\n"
        "        prompt = f'Data (JSON):\\n{json.dumps(data, indent=2)}\\n\\n'\\\n"
        "                 f'Chart spec:\\n{spec}'\n"
        "        response = client.models.generate_content(\n"
        "            model='gemini-2.5-flash',\n"
        "            contents=prompt,\n"
        "        )\n"
        "\n"
        "        # Strip markdown code fences if present\n"
        "        code_text = response.text.strip()\n"
        "        if '```python' in code_text:\n"
        "            code_text = code_text.split('```python', 1)[1].rsplit('```', 1)[0].strip()\n"
        "        elif '```' in code_text:\n"
        "            code_text = code_text.split('```', 1)[1].rsplit('```', 1)[0].strip()\n"
        "\n"
        "        print('=' * 70)\n"
        "        print('Generated matplotlib code — REVIEW BEFORE RUNNING:')\n"
        "        print('=' * 70)\n"
        "        print(code_text)\n"
        "        print('=' * 70)\n"
        "\n"
        "        # ⚠️ Code is from an LLM. Read it before executing.\n"
        "        # Flip to True once you trust the printed code.\n"
        "        RUN_CODE = False\n"
        "        if RUN_CODE:\n"
        "            exec(code_text)\n"
        "        else:\n"
        "            print('\\n(RUN_CODE=False — set to True above to execute.)')"
    ),
    md(
        "## 19. Metric glossary\n"
        "\n"
        "| Symbol / term | What it measures | Formula |\n"
        "|---------------|-----------------|----------|\n"
        "| **τ (tau)** | classification threshold on the sigmoid output: P(Pneumonia) ≥ τ ⇒ predict Pneumonia. Default τ=0.5 | — |\n"
        "| **Accuracy** | fraction of correct predictions over the **whole** test set | (TP + TN) / N |\n"
        "| **Sensitivity** (recall on Pneumonia) | of all true Pneumonia cases, how many did we catch? Critical for medical screening (don't miss disease) | TP / (TP + FN) |\n"
        "| **Specificity** (recall on Normal) | of all true Normal cases, how many did we correctly clear? Drives false-alarm rate | TN / (TN + FP) |\n"
        "| **AUROC** | area under the ROC curve. Threshold-*independent* discrimination quality. 0.5 = random, 1.0 = perfect | — |\n"
        "| **ECE** (Expected Calibration Error) | gap between predicted confidence and actual accuracy, averaged over confidence bins. Lower = better calibrated. <0.05 = well calibrated | Σ ⎮acc(b) − conf(b)⎮ · n(b)/N |\n"
        "\n"
        "*Why both sensitivity and specificity?* Accuracy hides which **direction** "
        "your errors go. In a screening setting, missing a Pneumonia (false negative) "
        "is much worse than a false alarm. Splitting accuracy into sensitivity (FN-rate) "
        "and specificity (FP-rate) makes that trade-off visible — and tunable via τ."
    ),
    md(
        "## 20. A1 — Depth ablation\n"
        "\n"
        "Number of conv-pool blocks. Glorot init at the winning depth is included as "
        "a controlled comparison: He init is a necessary condition at depth ≥ 4 for "
        "stacked ReLUs (He et al. 2015)."
    ),
    code(
        "import json, os, math\n"
        "import matplotlib.pyplot as plt\n"
        "\n"
        "RUNS_ROOT = os.environ.get('PNEUMONIA_RUNS', 'runs')\n"
        "\n"
        "def load_summary(name):\n"
        "    p = f'{RUNS_ROOT}/{name}/summary.json'\n"
        "    return json.load(open(p)) if os.path.exists(p) else None\n"
        "\n"
        "rows = []\n"
        "for n in [2, 3, 4, 5]:\n"
        "    s = load_summary(f'a1_d{n}')\n"
        "    if s:\n"
        "        rows.append((str(n), s['architecture']['n_params'], s['test_acc']))\n"
        "\n"
        "best_n = max(rows, key=lambda r: r[2])[0] if rows else '4'\n"
        "g = load_summary(f'a1_d{best_n}_glorot')\n"
        "if g:\n"
        "    rows.append((f'{best_n} (Glorot)', g['architecture']['n_params'], g['test_acc']))\n"
        "\n"
        "if not rows:\n"
        "    print('No A1 runs found yet — train them first.')\n"
        "else:\n"
        "    labels = [r[0] for r in rows]\n"
        "    accs = [r[2] for r in rows]\n"
        "    n_test = 624\n"
        "    sigma = math.sqrt(max(accs) * (1 - max(accs)) / n_test)\n"
        "    fig, ax = plt.subplots(figsize=(8, 4))\n"
        "    bars = ax.bar(labels, accs, color=['#1A73E8'] * (len(rows) - 1) + ['#D93025'])\n"
        "    ax.axhspan(max(accs) - sigma, max(accs) + sigma, alpha=0.12, color='gray',\n"
        "               label=f'±1σ noise floor ({sigma*100:.2f} pp)')\n"
        "    ax.axhline(0.95, linestyle='--', color='#33691E', alpha=0.7,\n"
        "               label='theoretical ceiling (~0.95 acc)')\n"
        "    ax.set_ylabel('Test accuracy'); ax.set_xlabel('Number of conv-pool blocks')\n"
        "    ax.set_ylim(min(accs) - 0.05, max(0.97, max(accs) + 0.02))\n"
        "    for b, v in zip(bars, accs):\n"
        "        ax.text(b.get_x() + b.get_width() / 2, v + 0.002, f'{v:.3f}',\n"
        "                ha='center', va='bottom', fontsize=9)\n"
        "    ax.legend(loc='lower right', fontsize=8)\n"
        "    ax.set_title('A1 — depth ablation')\n"
        "    plt.tight_layout(); plt.show()\n"
        "    print(f'\\nA1 winner (test): {best_n} blocks at {max(accs):.4f}')"
    ),
    md(
        "## 21. A2 — Stride / padding / activation\n"
        "\n"
        "Six representative variants at the A1 winning depth. Activation, padding, and "
        "stride-mode are varied; everything else held constant."
    ),
    code(
        "a2_runs = [\n"
        "    ('a2_relu_same_pool',    'ReLU + same + pool'),\n"
        "    ('a2_leaky_same_pool',   'LeakyReLU + same + pool'),\n"
        "    ('a2_gelu_same_pool',    'GELU + same + pool'),\n"
        "    ('a2_relu_valid_pool',   'ReLU + valid + pool'),\n"
        "    ('a2_relu_same_strided', 'ReLU + same + strided'),\n"
        "    ('a2_gelu_same_strided', 'GELU + same + strided'),\n"
        "]\n"
        "rows = [(lbl, load_summary(name)) for name, lbl in a2_runs]\n"
        "rows = [(lbl, s['test_acc']) for lbl, s in rows if s]\n"
        "if not rows:\n"
        "    print('No A2 runs found yet.')\n"
        "else:\n"
        "    labels = [r[0] for r in rows]; accs = [r[1] for r in rows]\n"
        "    fig, ax = plt.subplots(figsize=(10, 4.5))\n"
        "    bars = ax.barh(labels, accs, color='#7B1FA2')\n"
        "    ax.axvline(0.95, linestyle='--', color='#33691E', alpha=0.7,\n"
        "               label='theoretical ceiling (~0.95 acc)')\n"
        "    ax.set_xlabel('Test accuracy')\n"
        "    ax.set_xlim(min(accs) - 0.03, max(0.97, max(accs) + 0.02))\n"
        "    for b, v in zip(bars, accs):\n"
        "        ax.text(v + 0.001, b.get_y() + b.get_height() / 2, f'{v:.3f}',\n"
        "                va='center', fontsize=9)\n"
        "    ax.set_title('A2 — stride / padding / activation')\n"
        "    ax.legend(loc='lower right', fontsize=8)\n"
        "    ax.invert_yaxis()\n"
        "    plt.tight_layout(); plt.show()\n"
        "    winner = max(rows, key=lambda r: r[1])\n"
        "    print(f'\\nA2 winner: {winner[0]} at {winner[1]:.4f}')"
    ),
    md(
        "## 22. A3 — Regularisation\n"
        "\n"
        "Train-vs-val gap is the diagnostic for overfitting; a wide gap means the model "
        "memorises training data instead of generalising. The combination row is expected "
        "to close the gap most."
    ),
    code(
        "a3_runs = [('a3_none', 'none'), ('a3_bn', 'BN'), ('a3_dropout', 'dropout 0.3'),\n"
        "           ('a3_l2', 'L2'), ('a3_aug', 'augmentation'), ('a3_combo', 'combo')]\n"
        "rows = []\n"
        "for name, lbl in a3_runs:\n"
        "    s = load_summary(name)\n"
        "    h_path = f'{RUNS_ROOT}/{name}/history.json'\n"
        "    if s and os.path.exists(h_path):\n"
        "        h = json.load(open(h_path))\n"
        "        rows.append((lbl, h['train_acc'][-1] if h['train_acc'] else 0,\n"
        "                     s['best_val_acc'], s['test_acc']))\n"
        "if not rows:\n"
        "    print('No A3 runs found yet.')\n"
        "else:\n"
        "    labels = [r[0] for r in rows]\n"
        "    train = [r[1] for r in rows]; val = [r[2] for r in rows]; test = [r[3] for r in rows]\n"
        "    import numpy as np\n"
        "    x = np.arange(len(labels)); w = 0.27\n"
        "    fig, ax = plt.subplots(figsize=(10, 4.5))\n"
        "    ax.bar(x - w, train, w, label='train', color='#FFB74D')\n"
        "    ax.bar(x,     val,   w, label='val',   color='#1A73E8')\n"
        "    ax.bar(x + w, test,  w, label='test',  color='#33691E')\n"
        "    ax.axhline(0.95, linestyle='--', color='#D93025', alpha=0.7,\n"
        "               label='theoretical ceiling (~0.95 acc)')\n"
        "    ax.set_xticks(x); ax.set_xticklabels(labels, rotation=0)\n"
        "    ax.set_ylabel('Accuracy'); ax.set_title('A3 — regularisation: train / val / test')\n"
        "    ax.legend(loc='lower right'); ax.set_ylim(0.5, 1.02)\n"
        "    plt.tight_layout(); plt.show()\n"
        "    winner = max(rows, key=lambda r: r[3])\n"
        "    print(f'\\nA3 winner (test): {winner[0]} at {winner[3]:.4f} '\n"
        "          f'(train-val gap {winner[1]-winner[2]:+.3f})')"
    ),
    md(
        "## 23. Mixup / CutMix / Manifold Mixup demo\n"
        "\n"
        "Mixup α=0.2 on a pretrained backbone lost 0.64 pp test accuracy in our experiments. "
        "Pretrained class boundaries are already calibrated, so blending samples adds noise "
        "rather than regularisation. Manifold Mixup blends *features* not pixels — shown "
        "here on a 14×14 proxy of the last hidden layer."
    ),
    code(
        "demo_path = '_helpers/mixup_cutmix_demo.png'\n"
        "if not os.path.exists(demo_path):\n"
        "    !python _helpers/_mixup_cutmix_demo.py\n"
        "if os.path.exists(demo_path):\n"
        "    display(IPImage(demo_path))\n"
        "else:\n"
        "    print('Demo image not found — re-run after dataset has been downloaded.')"
    ),
    md(
        "## 24. Champion ensemble — medical KPIs\n"
        "\n"
        "Five-fold custom-CNN ensemble. Reports the four KPIs at three operating points: "
        "default τ=0.5, val-tuned best-accuracy τ, and sensitivity-targeted τ ≥ 0.97."
    ),
    code(
        "kpi_path = f'{RUNS_ROOT}/champion_ensemble/medical_kpis.json'\n"
        "if not os.path.exists(kpi_path):\n"
        "    print('Champion KPIs not yet computed (run section 11 first).')\n"
        "else:\n"
        "    k = json.load(open(kpi_path))\n"
        "    print(f'AUROC  = {k[\"auroc\"]:.4f}')\n"
        "    print(f'ECE    = {k[\"ece\"]:.4f}')\n"
        "    print(f'noise floor sigma = {k[\"noise_floor_sigma\"]:.4f}')\n"
        "    print()\n"
        "    print(f'{\"operating point\":<28}{\"τ\":>6}{\"acc\":>8}{\"sens\":>8}{\"spec\":>8}')\n"
        "    for name, op in k['operating_points'].items():\n"
        "        print(f'{name:<28}{op[\"threshold\"]:>6.3f}{op[\"acc\"]:>8.4f}'\n"
        "              f'{op[\"sensitivity\"]:>8.4f}{op[\"specificity\"]:>8.4f}')\n"
        "\n"
        "    # Reliability diagram: per-bin gap between confidence and accuracy\n"
        "    bins = [b for b in k['calibration_bins_uniform'] if b['n']]\n"
        "    if bins:\n"
        "        fig, ax = plt.subplots(figsize=(5.5, 5.5))\n"
        "        confs = [b['conf'] for b in bins]\n"
        "        accs  = [b['acc']  for b in bins]\n"
        "        sizes = [b['n']   for b in bins]\n"
        "        ax.plot([0.5, 1], [0.5, 1], 'k--', alpha=0.5, label='perfect calibration')\n"
        "        ax.scatter(confs, accs, s=[s*2 for s in sizes], color='#D93025', alpha=0.6,\n"
        "                   edgecolor='black', label='bin (size = n)')\n"
        "        ax.set_xlabel('avg predicted confidence (per bin)')\n"
        "        ax.set_ylabel('observed accuracy (per bin)')\n"
        "        ax.set_xlim(0.5, 1.0); ax.set_ylim(0.5, 1.02)\n"
        "        ax.set_title(f'Reliability diagram — ECE={k[\"ece\"]:.3f}')\n"
        "        ax.legend(loc='upper left'); plt.tight_layout(); plt.show()"
    ),
    md(
        "## 25. Transfer-learning baselines — medical KPIs\n"
        "\n"
        "Three transfer-learning approaches with **explicitly different ablation depth**:\n"
        "- **ResNet50 + ImageNet** — generic pretraining, *full fine-tune* (LR/batch tuned)\n"
        "- **BiomedCLIP** — biomedical literature pretraining, *frozen features + linear probe*\n"
        "- **RAD-DINO** — chest-X-ray pretraining, *frozen features + linear probe*\n"
        "\n"
        "BiomedCLIP and RAD-DINO numbers carry the leakage caveats from §16 and §17."
    ),
    code(
        "for label, run_name in [('ResNet50 + ImageNet (full fine-tune)', 'ensemble'),\n"
        "                         ('BiomedCLIP + linear probe (PubMed pretraining)', 'biomedclip_ensemble'),\n"
        "                         ('RAD-DINO + linear probe (chest-X-ray pretraining)', 'rad_dino_ensemble')]:\n"
        "    path = f'{RUNS_ROOT}/{run_name}/medical_kpis.json'\n"
        "    print(f'\\n=== {label} ===')\n"
        "    if not os.path.exists(path):\n"
        "        print(f'  KPIs not yet computed at {path}')\n"
        "        continue\n"
        "    k = json.load(open(path))\n"
        "    print(f'  AUROC  = {k[\"auroc\"]:.4f}')\n"
        "    print(f'  ECE    = {k[\"ece\"]:.4f}')\n"
        "    print(f'  {\"operating point\":<28}{\"τ\":>6}{\"acc\":>8}{\"sens\":>8}{\"spec\":>8}')\n"
        "    for opname, op in k['operating_points'].items():\n"
        "        print(f'  {opname:<28}{op[\"threshold\"]:>6.3f}{op[\"acc\"]:>8.4f}'\n"
        "              f'{op[\"sensitivity\"]:>8.4f}{op[\"specificity\"]:>8.4f}')"
    ),
    md(
        "## 26. Headline comparison — 4 KPIs across approaches\n"
        "\n"
        "Single comparison figure: each approach × four KPIs. Best-accuracy threshold "
        "is used for sensitivity and specificity (the natural single-point summary). "
        "Leakage caveats from §16 and §17 apply to the BiomedCLIP and RAD-DINO bars."
    ),
    code(
        "approaches = [\n"
        "    ('Custom CNN (from scratch, 5-fold)',                  f'{RUNS_ROOT}/champion_ensemble/medical_kpis.json'),\n"
        "    ('ResNet50 + ImageNet (generic pretraining, 5-fold)',  f'{RUNS_ROOT}/ensemble/medical_kpis.json'),\n"
        "    ('BiomedCLIP probe (PubMed pretraining, 5-fold)',      f'{RUNS_ROOT}/biomedclip_ensemble/medical_kpis.json'),\n"
        "    ('RAD-DINO probe (chest-X-ray pretraining, 5-fold)',   f'{RUNS_ROOT}/rad_dino_ensemble/medical_kpis.json'),\n"
        "]\n"
        "loaded = []\n"
        "for label, path in approaches:\n"
        "    if os.path.exists(path):\n"
        "        k = json.load(open(path))\n"
        "        op = k['operating_points'].get('best_accuracy', list(k['operating_points'].values())[0])\n"
        "        loaded.append({\n"
        "            'label': label,\n"
        "            'sensitivity': op['sensitivity'],\n"
        "            'specificity': op['specificity'],\n"
        "            'auroc': k['auroc'],\n"
        "            'one_minus_ece': 1 - k['ece'],\n"
        "        })\n"
        "\n"
        "if not loaded:\n"
        "    print('No champion or transfer-learning KPIs available yet.')\n"
        "else:\n"
        "    import numpy as np\n"
        "    metrics = ['sensitivity', 'specificity', 'auroc', 'one_minus_ece']\n"
        "    metric_labels = ['Sensitivity', 'Specificity', 'AUROC', '1 − ECE\\n(higher = better calibrated)']\n"
        "    n_app = len(loaded); x = np.arange(len(metrics)); w = 0.8 / max(n_app, 1)\n"
        "    fig, ax = plt.subplots(figsize=(10, 5))\n"
        "    colors = ['#D93025', '#1A73E8', '#33691E', '#7B1FA2']\n"
        "    for i, app in enumerate(loaded):\n"
        "        vals = [app[m] for m in metrics]\n"
        "        bars = ax.bar(x + i * w - w * (n_app - 1) / 2, vals, w,\n"
        "                       label=app['label'], color=colors[i])\n"
        "        for b, v in zip(bars, vals):\n"
        "            ax.text(b.get_x() + b.get_width() / 2, v + 0.005, f'{v:.3f}',\n"
        "                    ha='center', va='bottom', fontsize=8)\n"
        "\n"
        "    # Per-metric clinical-usability minimum and theoretical-ceiling segments.\n"
        "    # Thresholds vary per metric — see Appendix A (ceiling) and Appendix B (usability).\n"
        "    thresholds = {\n"
        "        'sensitivity':   {'min': 0.95, 'ceiling': 0.97},\n"
        "        'specificity':   {'min': 0.90, 'ceiling': 0.95},\n"
        "        'auroc':         {'min': 0.95, 'ceiling': 0.98},\n"
        "        'one_minus_ece': {'min': 0.90, 'ceiling': 0.95},\n"
        "    }\n"
        "    half = (n_app * w) / 2 + 0.05\n"
        "    for i, m in enumerate(metrics):\n"
        "        t = thresholds[m]\n"
        "        ax.hlines(t['min'], x[i] - half, x[i] + half,\n"
        "                  colors='#D93025', linestyles='--', alpha=0.7, linewidth=1.4)\n"
        "        ax.hlines(t['ceiling'], x[i] - half, x[i] + half,\n"
        "                  colors='#33691E', linestyles='--', alpha=0.7, linewidth=1.4)\n"
        "    # Empty plots just to populate the legend with the reference-line labels.\n"
        "    ax.plot([], [], '--', color='#D93025', alpha=0.7, linewidth=1.4,\n"
        "            label='Clinical-usability minimum (per metric)')\n"
        "    ax.plot([], [], '--', color='#33691E', alpha=0.7, linewidth=1.4,\n"
        "            label='Theoretical ceiling (per metric)')\n"
        "\n"
        "    ax.set_xticks(x); ax.set_xticklabels(metric_labels)\n"
        "    ax.set_ylim(0, 1.05); ax.set_ylabel('Score')\n"
        "    ax.set_title('Headline KPI comparison (reference lines: per metric)')\n"
        "    ax.legend(loc='lower right', fontsize=8)\n"
        "    plt.tight_layout()\n"
        "    plt.savefig(f'{RUNS_ROOT}/champion_ensemble/headline_kpi_comparison.png', dpi=120)\n"
        "    plt.show()\n"
        "\n"
        "    print()\n"
        "    print(f'{\"approach\":<40}{\"sens\":>8}{\"spec\":>8}{\"AUROC\":>8}{\"ECE\":>8}')\n"
        "    print('-' * 72)\n"
        "    for app in loaded:\n"
        "        print(f'{app[\"label\"]:<40}{app[\"sensitivity\"]:>8.4f}'\n"
        "              f'{app[\"specificity\"]:>8.4f}{app[\"auroc\"]:>8.4f}'\n"
        "              f'{1 - app[\"one_minus_ece\"]:>8.4f}')"
    ),
    md(
        "### Optional — Claude vision critique of the headline chart\n"
        "\n"
        "Sends the just-generated headline KPI image to Claude (claude-sonnet-4-6, "
        "vision-enabled) with a critique prompt. Useful catch for missing labels, "
        "accessibility issues, or visualisation choices that may mislead a reader. "
        "Requires `ANTHROPIC_API_KEY` in Colab Secrets — get one at "
        "https://console.anthropic.com/settings/keys (new accounts get $5 free credits)."
    ),
    code(
        "import os, base64\n"
        "try:\n"
        "    from google.colab import userdata\n"
        "    anthropic_key = userdata.get('ANTHROPIC_API_KEY')\n"
        "except Exception:\n"
        "    anthropic_key = os.environ.get('ANTHROPIC_API_KEY')\n"
        "\n"
        "chart_path = f'{RUNS_ROOT}/champion_ensemble/headline_kpi_comparison.png'\n"
        "\n"
        "if not anthropic_key:\n"
        "    print('No ANTHROPIC_API_KEY — set it in Colab Secrets to enable.')\n"
        "elif not os.path.exists(chart_path):\n"
        "    print(f'No chart at {chart_path} — run the previous cell first.')\n"
        "else:\n"
        "    !pip install -q anthropic\n"
        "    from anthropic import Anthropic\n"
        "\n"
        "    with open(chart_path, 'rb') as f:\n"
        "        img_b64 = base64.standard_b64encode(f.read()).decode()\n"
        "\n"
        "    client = Anthropic(api_key=anthropic_key)\n"
        "    msg = client.messages.create(\n"
        "        model='claude-sonnet-4-6',\n"
        "        max_tokens=1024,\n"
        "        messages=[{\n"
        "            'role': 'user',\n"
        "            'content': [\n"
        "                {'type': 'image', 'source': {\n"
        "                    'type': 'base64',\n"
        "                    'media_type': 'image/png',\n"
        "                    'data': img_b64\n"
        "                }},\n"
        "                {'type': 'text', 'text':\n"
        "                    'Critique this chart for an academic medical-AI report. '\n"
        "                    'Cover: (1) missing or unclear labels; (2) accessibility '\n"
        "                    'issues (colour contrast, font size, colourblind safety); '\n"
        "                    '(3) potential misinterpretations a reader might make; '\n"
        "                    '(4) what could be added to clarify the trade-offs. '\n"
        "                    'Keep under 300 words, bullet points, neutral tone.'\n"
        "                }\n"
        "            ]\n"
        "        }]\n"
        "    )\n"
        "    print('=' * 70)\n"
        "    print(\"Claude's critique:\")\n"
        "    print('=' * 70)\n"
        "    print(msg.content[0].text)"
    ),
    md(
        "## 27. Conclusion\n"
        "\n"
        "**What worked.**\n"
        "- A 4-block ReLU CNN with same-padding and max-pool gives a solid from-scratch "
        "baseline. Depth ≥ 5 adds parameters without measurable test-accuracy gain.\n"
        "- He (kaiming) initialisation is necessary at depth ≥ 4; Glorot fails to train "
        "stacked-ReLU networks of this depth (vanishing pre-activations).\n"
        "- The combination of BatchNorm + dropout + augmentation closes the train-vs-val "
        "gap most effectively. Single regularisers add 0.3–0.7 pp; combinations are "
        "additive but with diminishing returns.\n"
        "- Threshold tuning rebalances the false-negative-vs-false-positive cost without "
        "retraining; the model's underlying discrimination (AUROC) is unchanged.\n"
        "- Generic pretraining (ImageNet) raises the headline accuracy but does not "
        "necessarily improve calibration (ECE).\n"
        "- Biomedical-literature pretraining (BiomedCLIP, ~15M PubMed image-text pairs) "
        "and chest-X-ray-specific pretraining (RAD-DINO, ~877K chest X-rays) typically "
        "give another step up over generic pretraining — *with the leakage caveats below*.\n"
        "\n"
        "**What did not work.**\n"
        "- Mixup α=0.2 on a pretrained backbone lost 0.64 pp — pretrained class boundaries "
        "are already calibrated.\n"
        "- SNR-AdamW underperformed standard AdamW by ~7 pp on this task — its theoretical "
        "advantages target noisier domains.\n"
        "- Temperature scaling did not move the from-scratch model's ECE in the expected "
        "direction; the model is *under-confident* rather than over-confident.\n"
        "\n"
        "**Methodological position.** The official Kaggle test set is patient-isolated by "
        "construction; our reported KPIs reflect honest performance on unseen patients. "
        "Numerical overlap of 170 PNE person-IDs between train and test is an artefact of "
        "per-split renumbering, not real leakage.\n"
        "\n"
        "**Leakage caveats — medical-domain pretraining.**\n"
        "- *RAD-DINO* was pretrained on MIMIC-CXR, CheXpert, PadChest, NIH ChestX-ray14, "
        "BRAX, and VinDr-CXR — chest X-ray datasets that share acquisition protocols and "
        "anatomy distributions with Kermany. The Kermany dataset itself is not in the list, "
        "but distribution-level overlap is plausible.\n"
        "- *BiomedCLIP* was pretrained on ~15M image-text pairs from PubMed Open Access — "
        "mostly biomedical literature illustrations, microscopy and figure panels rather "
        "than direct chest X-rays. Less acute leakage risk than RAD-DINO, but still warrants "
        "a caveat.\n"
        "- *Reading the KPIs*: BiomedCLIP and RAD-DINO numbers should be interpreted as "
        "upper-bound indications of medical-domain transfer, not as directly comparable "
        "points with the from-scratch and ImageNet baselines.\n"
        "\n"
        "**Heterogeneous ablation depth across approaches**: only the custom CNN track has "
        "deep architectural ablation (A1/A2/A3). The pretrained tracks are fixed black-box "
        "feature extractors or fine-tuned with shallow hyperparameter tuning only — their "
        "architecture is not ours to design. This asymmetry is intentional and reflected "
        "in §16-§17 cell descriptions and the methodology flow diagram (Stage 3).\n"
        "\n"
        "**On the Kaggle Chest X-Ray Pneumonia (Kermany 2018) dataset, the realistically "
        "achievable ceiling is around sensitivity 96-97 % and specificity 92-95 % — see "
        "Appendix A in REPORT_TABLES.md.**"
    ),
    md(
        "### Optional — Claude-drafted alternative conclusion paragraph\n"
        "\n"
        "Reads the actual KPIs from every `medical_kpis.json` on disk and asks Claude "
        "(claude-sonnet-4-6) to draft a 200-word academic conclusion paragraph. Useful "
        "as a starting point for the report-writing phase — review and edit before "
        "using. Requires `ANTHROPIC_API_KEY` in Colab Secrets."
    ),
    code(
        "import os, json\n"
        "try:\n"
        "    from google.colab import userdata\n"
        "    anthropic_key = userdata.get('ANTHROPIC_API_KEY')\n"
        "except Exception:\n"
        "    anthropic_key = os.environ.get('ANTHROPIC_API_KEY')\n"
        "\n"
        "if not anthropic_key:\n"
        "    print('No ANTHROPIC_API_KEY — set it in Colab Secrets to enable.')\n"
        "else:\n"
        "    !pip install -q anthropic\n"
        "    from anthropic import Anthropic\n"
        "\n"
        "    kpi_paths = {\n"
        "        'Custom CNN (from scratch, A1/A2/A3 ablations)': f'{RUNS_ROOT}/champion_ensemble/medical_kpis.json',\n"
        "        'ResNet50 + ImageNet (full fine-tune)':           f'{RUNS_ROOT}/ensemble/medical_kpis.json',\n"
        "        'BiomedCLIP linear probe (PubMed pretraining)':   f'{RUNS_ROOT}/biomedclip_ensemble/medical_kpis.json',\n"
        "        'RAD-DINO linear probe (chest-X-ray pretraining)':f'{RUNS_ROOT}/rad_dino_ensemble/medical_kpis.json',\n"
        "    }\n"
        "    summary = {}\n"
        "    for label, path in kpi_paths.items():\n"
        "        if os.path.exists(path):\n"
        "            k = json.load(open(path))\n"
        "            op_keys = list(k['operating_points'].keys())\n"
        "            op = k['operating_points'].get('best_accuracy', k['operating_points'][op_keys[0]])\n"
        "            summary[label] = {\n"
        "                'sensitivity': round(op['sensitivity'], 4),\n"
        "                'specificity': round(op['specificity'], 4),\n"
        "                'auroc': round(k['auroc'], 4),\n"
        "                'ece': round(k['ece'], 4),\n"
        "            }\n"
        "\n"
        "    if not summary:\n"
        "        print('No medical KPIs available — train and evaluate the approaches first.')\n"
        "    else:\n"
        "        prompt = (\n"
        "            f'Draft a 200-word conclusion paragraph for an academic medical-AI '\n"
        "            f'report comparing four approaches on the Kaggle Chest X-Ray '\n"
        "            f'Pneumonia dataset. Use these actual measured KPIs:\\n\\n'\n"
        "            f'{json.dumps(summary, indent=2)}\\n\\n'\n"
        "            f'Requirements:\\n'\n"
        "            f'- Identify the highest-AUROC approach.\\n'\n"
        "            f'- Note calibration trade-offs (ECE).\\n'\n"
        "            f'- Mention the leakage caveat for medical-domain pretrained models '\n"
        "            f'  (BiomedCLIP, RAD-DINO).\\n'\n"
        "            f'- Highlight that only the custom CNN track has architectural ablations; '\n"
        "            f'  the others are direct applications of fixed pretrained models.\\n'\n"
        "            f'- Neutral academic tone, no marketing language.\\n'\n"
        "            f'- Output the paragraph only, no preamble.'\n"
        "        )\n"
        "        client = Anthropic(api_key=anthropic_key)\n"
        "        msg = client.messages.create(\n"
        "            model='claude-sonnet-4-6',\n"
        "            max_tokens=600,\n"
        "            messages=[{'role': 'user', 'content': prompt}]\n"
        "        )\n"
        "        print('=' * 70)\n"
        "        print(\"Claude's draft conclusion (review and edit before using):\")\n"
        "        print('=' * 70)\n"
        "        print(msg.content[0].text)"
    ),
    md(
        "## 28. Future work\n"
        "\n"
        "1. **Higher input resolution** (320 / 384) — pneumonia opacities are subtle and "
        "may benefit from finer sampling.\n"
        "2. **Label-noise audit** on the high-confidence-wrong subset.\n"
        "3. **Three-class formulation** (NORMAL / BACTERIAL / VIRAL) — bacterial vs. viral "
        "labels are encoded in filenames but not modelled.\n"
        "4. **Multi-seed protocol** (3 seeds × 5 folds) for honest 95 % CIs on test accuracy.\n"
        "5. **Patient-aware K-fold** via `GroupKFold` for a more conservative internal CV "
        "estimate; test KPIs unaffected by construction.\n"
        "6. **Class-prior rescaling** (Bayesian) to mitigate the train-vs-test PNE prevalence "
        "shift (74 % → 62.5 %)."
    ),
]


NOTEBOOK = {
    "cells": CELLS,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {"name": "python", "version": "3.10"},
        "colab": {"provenance": []},
        "accelerator": "GPU",
    },
    "nbformat": 4,
    "nbformat_minor": 0,
}


if __name__ == "__main__":
    OUT.write_text(json.dumps(NOTEBOOK, indent=1, ensure_ascii=False), encoding="utf-8")
    print(f"Wrote {OUT} ({len(CELLS)} cells)")
